name: Code Quality Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Обновляем экшен до стабильной версии
    - name: Set up uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      run: uv python install 3.11

    - name: Install dependencies from Lock-file
      run: |
        uv sync --all-groups

    - name: Lint with Ruff
      run: |
        uv run ruff check src/

    - name: Type check with Mypy
      run: |
        uv run mypy --ignore-missing-imports src/

    # Запуск тестов. Теперь, когда в файле есть реальный assert, pytest вернет код 0
    - name: Run tests with pytest
      run: |
        uv run pytest tests/
