name: Code Quality Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Скачиваем код репозитория (Обновленная версия для Node24)
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    # 2. Устанавливаем uv (Обновленная стабильная версия)
    - name: Set up uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    # 3. Устанавливаем Python 3.11 через uv
    - name: Set up Python
      run: uv python install 3.11

    # 4. Синхронизируем окружение по uv.lock
    - name: Install dependencies from Lock-file
      run: |
        uv sync --all-groups

    # 5. Проверка стиля кода через встроенный вызов uv run
    - name: Lint with Ruff
      run: |
        uv run ruff check src/
    #  continue-on-error: true # Позволяет увидеть отчет, но не красит крестик в красный

    # 6. Проверка строгой типизации через встроенный вызов uv run
    - name: Type check with Mypy
      run: |
        uv run mypy --ignore-missing-imports src/
      #continue-on-error: true

    # 7. Автоматический запуск Unit-тестов
    - name: Run tests with pytest
      run: |
        uv run pytest tests/
      #continue-on-error: true
